BEGIN TRANSACTION;
DELETE FROM TEST WHERE ID=66;
INSERT INTO TEST(ID,NUME) VALUES(100,'XXXX');
COMMIT


--CREATE TABLE CUSTOMER(
-- id SERIAL PRIMARY KEY,
-- NUME VARCHAR(128),
-- VARSTA INTEGER,
-- SEX CHAR(1)
 
--)
--INSERT INTO CUSTOMER(NUME,VARSTA,SEX) VALUES('VIVI',14,'F')
--CREATE TABLE VANZARI(
--  ID SERIAL PRIMARY KEY,
--  DATA_VANZARE TIMESTAMP,
--  NUME_MARFA VARCHAR(64),
--  VALOARE NUMERIC(10,2),
--  CUSTOMER_ID INTEGER,
--  FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID)
--)
INSERT INTO VANZARI(DATA_VANZARE,NUME_MARFA,VALOARE,CUSTOMER_ID)
  VALUES(TIMESTAMPADD(DAY,-1,NOW()),'HALAT', 101.24, 4)
  
  
  
  --SELECT *,now() AS data_de_acum FROM TEST WHERE id >= 11 ORDER BY ID DESC
--SELECT count(DISTINCT NUME) FROM TEST
--SELECT nume,avg(id) AS avg_ids,count(id) FROM TEST WHERE id>=11 GROUP BY NUME   HAVING avg(id) > 49 
--CREATE TABLE PUFI AS 

--SELECT C.ID,C.NUME,C.VARSTA,V.NUME_MARFA AS NM,V.VALOARE  FROM CUSTOMER C 
-- JOIN VANZARI V  ON C.ID=V.CUSTOMER_ID

--SELECT C.ID,C.NUME,C.VARSTA AS VRST, T.NUME_MARFA ,T.VALOARE
--  FROM CUSTOMER C,(SELECT * FROM VANZARI) AS T
--   WHERE T.CUSTOMER_ID=C.ID

--SELECT C.SEX, SUM(V.VALOARE) AS TOTAL,SUM(V.VALOARE*0.19) AS TVA FROM 
--  CUSTOMER C JOIN VANZARI V ON C.ID=V.CUSTOMER_ID
--  GROUP BY C.SEX
--SELECT V.NUME_MARFA , COUNT(C.ID) FROM CUSTOMER C,VANZARI V  WHERE C.ID=V.CUSTOMER_ID GROUP BY V.NUME_MARFA
SELECT EXTRACT(MONTH FROM V.DATA_VANZARE) AS MONTH, SUM(V.VALOARE) AS VALOARE FROM VANZARI V 
  GROUP BY EXTRACT(MONTH FROM V.DATA_VANZARE)

  
  --CREATE TABLE test(id INTEGER PRIMARY KEY,nume VARCHAR(16)) 
--ALTER TABLE test ADD COLUMN inaltime FLOAT
--INSERT INTO test(id,nume,INALTIME) VALUES(55,'SPUMEEE',4.56), (66,'HAHA',77)
--UPDATE TEST SET nume='NUMEEEEE',INALTIME=3.14 WHERE (ID=33) AND (NUME IS NOT NULL);
--DELETE FROM TEST WHERE INALTIME=33
--SELECT * FROM TEST WHERE ID IS NOT NULL
-- INSERT INTO TEST(ID,NUME) SELECT xx,yy FROM ZZ WHERE ... 
INSERT INTO test(id,nume,INALTIME) VALUES(77,'123456789012345',22.56)
